#!/bin/sh

# First change to the directory where this script is located on. The
# following works even if this script is run trhough a symlink. Copied
# from # https://stackoverflow.com/a/246128

SOURCE=${BASH_SOURCE[0]}
while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

ORIGINAL_DIR=$(pwd)

cd $( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

CLASSPATH=$(clojure -Spath)

# Replace leading "." with the absolute path to deps.edn directory
CLASSPATH=$(echo "$CLASSPATH" | sed "s|^\.|$(pwd)|")

cd "$ORIGINAL_DIR"

clojure -Scp "$CLASSPATH" -M -m core "$@"
